### ISSUE TITLE
we need the new MEG console to be supported

### ISSUE THREAD

**Issue by robertoostenveld** [Donders-Institute/data-streamer#12]
its hostname is lab-meg001, the user name and password are the same as on the old console. 

Below you can see and compare the location of the data.

```
[meg@odin ~]$ ls /ctfmeg/odin/data/meg/ACQ_Data/
20161209  20161212  20161213  20161214  20161215  20161216  20161219  20161220  20161221  20161222  20161223
```

```
[meg@lab-meg001 ~]$ ls /ctfmeg/ACQ_Data/
20161223 
```

**Comment by hurngchunlee** [comment]
It's done.  Main changes are in this commit: https://github.com/Donders-Institute/streamer/commit/e06eae3df29c2236df9f02fdc8b8cadf4ea1e6c8

To initiate a streamer data flow from lab-meg001, make a POST request using the URL below:

- `http://pacs.dccn.nl:3001/meg-new/<date>` (for all datasets produced in the given date), or 
- `http://pacs.dccn.nl:3001/meg-new/<date>/<dataset>.ds` (for a dataset produced in a given date)

**Comment by hurngchunlee** [comment]
@robertoostenveld please test it and close the issue if it works properly.

**Comment by robertoostenveld** [comment]
I get an "Unauthorized" as answer. Also when logging in with a browser on pacs.dccn.nl:3001 I am confronted with a authentication dialog.

... ah, I forgot the "-u user:pwd" option for curl.

It is working, i.e. it is scheduled properly and ends up on central storage in the catch-all collection. I presume it also ends up at the other locations.
