### ISSUE TITLE
As a product owner, I want to see a complete design diagram of the streamer and streamer-ui components

### ISSUE THREAD

**Issue by hurngchunlee** [Donders-Institute/data-streamer#19]
A component diagram is sufficient.

Also illustrate the dataflow to project as well as the DR.

The diagrams should show the internal design of the two components, as well as interactions between components.

**Comment by rutgervandeelen** [comment]
Draft Powerpoint slide and figure can be found on the `tg` groupshare `Projects\Project Streamer UI` folder.

![data-streamer-ui](https://user-images.githubusercontent.com/11499399/63167205-dd94f200-c030-11e9-8e5d-542899aba793.png)

**Comment by hurngchunlee** [comment]
@rutgervandeelen I forgot one more thing, could you add a box right to the `Streamer` box with text label `Stager`, and draw a line from the `Streamer` box to the `Stager` box with HTTP POST.  The `Stager` box should also have a line to the `Project Storage`.

**Comment by rutgervandeelen** [comment]
Updated figure. Added `stager`, `stager ui` and `project database` components.

![data-streamer-ui](https://user-images.githubusercontent.com/11499399/63176640-99ace780-c046-11e9-8bd7-d5bd7dae1e81.png)
