### ISSUE TITLE
Implement streamer ui component

### ISSUE THREAD

**Issue by hurngchunlee** [Donders-Institute/data-streamer#22]
so that the user can interact with it using the web browser, and upload files to the buffer of the streamer ui.

**Comment by hurngchunlee** [comment]
The stream ui should maintain the data uploaded by user to an intermediate buffer space that is shared with the streamer service.

The directory structure on this buffer is

`/streamer-ui-buffer/`

**Comment by rutgervandeelen** [comment]
A basic version of the streamer ui component has been implemented. It is now possible to upload files to the project storage via `https://streamer-acc.dccn.nl`
