### ISSUE TITLE
Clean-up .streamer file

### ISSUE THREAD

**Issue by marcelzwiers** [Donders-Institute/data-streamer#221]
After uploading of data there is an empty `.streamer` file in the target directory, could this be cleaned up?

**Comment by hurngchunlee** [comment]
This is the file touched to check whether the user has write permission to upload data to the given project folder.  I will remove it after the check is done.

**Comment by hurngchunlee** [comment]
@marcelzwiers this should have been fixed.  Could you check it and let me know if this issue can be closed?

**Comment by rutgervandeelen** [comment]
Fixed, tested and deployed in release 3.0.3 (see commit ff7c2d3b7968207f1233a2fdfc278c1ab39c0977)
