### ISSUE TITLE
Create a mock-up of the streamer ui

### ISSUE THREAD

**Issue by hurngchunlee** [Donders-Institute/data-streamer#23]
so that the design of the interface can be discussed and finalized before implementation.

* how to upload files?
* how to provide attributes such as `project id`, `subject id`, `session id`, and `data type`. 
    - authentication is a key to avoid mistake in streaming data to a wrong project.
    - `data_type` should consists predefined labels as well as `other` by which user can provides his own data_type.

**Comment by rutgervandeelen** [comment]
I started on a mockup of the data-streamer-ui in https://github.com/Donders-Institute/data-streamer-ui-mockup

**Comment by hurngchunlee** [comment]
@rutgervandeelen I don't see the point of making a new repository just for mock-up.

Why don't you just put the codes/docs within the streamer repository under a `ui` subdirectory?  I assume the mock-up codes can be used further for implementing the real ui webservice.

**Comment by rutgervandeelen** [comment]
I have removed the private repository https://github.com/Donders-Institute/data-streamer-ui-mockup and put the source code in the `ui` directory instead.

**Comment by hurngchunlee** [comment]
@rutgervandeelen Great! But just for consistency, maybe it is better to relocate the `ui` folder in the data streamer repository under the `docker` folder, and rename the folder to `streamer-ui`.  This aligns with the folder structure of the [stager repository](https://github.com/Donders-Institute/data-stager).

**Comment by rutgervandeelen** [comment]
Much clearer indeed. I moved the `ui` folder to the `docker/streamer-ui` folder.

**Comment by hurngchunlee** [comment]
Have tried the mock-up, here are few things I think can be improved:

- If I drag-drop the same file twice into the upload list, it was accepted.  I think it should shown an error indicating that there has already a file with the same name in the upload list.
- I cannot remove file from the upload file list.  This should be allowed.
- When selecting the 'Other' data type, a text field should be shown allowing me to provide the name of the type.  The input value of the text field should not contain special characters.

**Comment by rutgervandeelen** [comment]
Good remark. 
The first two bullets have been covered in commit d2b26f7e1b39c59a041530553d23e81eaa111335. 
The last bullet still needs to be implemented.

**Comment by robertoostenveld** [comment]
Looking at https://github.com/Donders-Institute/data-streamer/blob/master/docker/streamer-ui/docs/screenshot-data-streamer-ui.png I propose that subject and session are split in two separate text entry fields. Also, the default datatypes should be all lowercase; please implement it first for mri, meg, eeg, ieee, beh, other.

**Comment by rutgervandeelen** [comment]
I have added the following:
* all lowercase default datatypes `mri`, `meg`, `eeg`, `ieee`, `beh`, `other`
* two separate dropdowns for subject and session
* updated screenshot

See commits 3c90a0f29814433b6e15d0d3ace835952ce86f5f, 47967b798b9a5d05084665dd2eda7db94ccfce68 and 6786cbfb6b41ef45a83cdec34c2932a8d18465c2.

Validation of the `other` data type input field is not implemented yet.
