### ISSUE TITLE
transition to new data flow

### ISSUE THREAD

**Issue by robertoostenveld** [Donders-Institute/data-streamer#4]
up to now we had (as cron under roboos@mentat001)

meg_copy.sh from odin to catch-all on central storage 
meg_organize.sh from catch all to project organization on central storage
meg_archive.sh from catch-all on odin to catch-all on RDM
meg_cleanup.sh
meg_quality.sh

**Comment by robertoostenveld** [comment]
the first three are not needed any more and I have just disabled them in my nightly cron job.

**Comment by robertoostenveld** [comment]
@hurngchunlee right now we don't have the automatic triggering of data flow from odin to central storage in place. Prior to updating the end-user interface, I'll start with a cron job on odin:

```
15 4 * * *  $HOME/bin/stream_data.sh
```

which executes this

```
#!/bin/bash

# get the date formatted as YYYMMDD
YESTERDAY=`date +%Y%m%d --date="yesterday"`
TODAY=`date +%Y%m%d`

# stream the most recent data
curl -X POST -u xxx http://pacs.dccn.nl:3001/meg/$YESTERDAY
curl -X POST -u xxx http://pacs.dccn.nl:3001/meg/$TODAY
```

I just triggered the POST for yesterday.

**Comment by robertoostenveld** [comment]
bummer, it failed. @hurngchunlee can you have a look at job 3 at http://pacs.dccn.nl:3001/failed

**Comment by hurngchunlee** [comment]
Yes, I am on it.  Looks a trivial bug.

**Comment by hurngchunlee** [comment]
Hmm ... I overlooked one for loop and therefore the callback is called multiple times and therefore the error ... just fixed it in this commit: https://github.com/Donders-Institute/meg-dataflow/commit/8dff0dcd4d1f8a3e577f96d5f651ca5d7e0a10cc

Also rerun the job and it now succeeded.

btw, the error is in the control loop; all staging and rsync tasks have already been performed correctly while this error occurred.  Thus, the rerun simply did nothing ... 

Maybe you could try again with another date?

**Comment by hurngchunlee** [comment]
The dataflow has been in production for a while.  Closing the issue.
