### ISSUE TITLE
As a user, I want the title of the data streamer email to be correct

### ISSUE THREAD

**Issue by rutgervandeelen** [Donders-Institute/data-streamer#44]
so that I can go to the folder of interest on the project storage.

- [x] Add missing `/raw` directory in title of streamer email

**Comment by hurngchunlee** [comment]
The email content is constructed with the stremer job title.  I have fixed the job title by adding the missing '/raw/'.  See commit: https://github.com/Donders-Institute/data-streamer/commit/b0d60b2025c3eccb35481dbde73b16213b7675e3
