### ISSUE TITLE
As a user, I want to submit the login form by pressing enter

### ISSUE THREAD

**Issue by rutgervandeelen** [Donders-Institute/data-streamer#45]
so that I do not have to click on the button.

- [ ] Allow submit with `enter` key

**Comment by tomwalsh-home** [comment]
Id like to give this a go. I can start tomorrow?

**Comment by rutgervandeelen** [comment]
@tomwalsh-home We have already solved the issue. Thank you for offering your help, but I think it is very impractical for you to contribute to this project if you are not a checked in user of the Donders Centre for Cognitive Neuroimaging (DCCN).

**Comment by rutgervandeelen** [comment]
See commit 00522d1a04a591ded78288ce714c1aef6fa16a39
