### ISSUE TITLE
As a product owner I want the maximum file size to be set to 1 GB

### ISSUE THREAD

**Issue by rutgervandeelen** [Donders-Institute/data-streamer#51]
so that users can upload files larger than 1 MB.

- [x] Add line `client_max_body_size 1000M;` to NGNINX configuration
- [x] Update streamer ui client max file size settings

**Comment by hurngchunlee** [comment]
I have set the webapp-proxy service of the acceptance with the following additional NGINX configuration
```
        # allow up to 1 GB file upload
        client_max_body_size 1024m;

        # extend proxy timeout to allow large file transfer
        proxy_connect_timeout       5m;
        proxy_send_timeout          5m;
        proxy_read_timeout          5m;
        send_timeout                5m;
```

**Comment by rutgervandeelen** [comment]
Updated the streamer-ui client to allow 1 GB files and 5 minutes upload time for a single file. See commit ada358633d2af6ea2288a691c973a43a2f058fa2
