### ISSUE TITLE
As a product owner I want to have usage statistics of the data streamer

### ISSUE THREAD

**Issue by rutgervandeelen** [Donders-Institute/data-streamer#56]
so that I have insight into how the data streamer is used.

- [x] Enrich the logging of the streamer-ui server 
- [x] Store the following information:
  * username
  * ip address
  * start [timestamp]
  * end [timestamp]
  * max filesize [bytes]
  * number of files
  * total upload size [bytes]  
  * user agent (i.e. web browser, operating system)
  * error if any
- [x] wontfix Make end point that gives stats report. It must provide the following information:
  * Unique user count
  * Number of sessions count
  * Total bytes uploaded since start
  * Top users - uploaded [bytes]
  * Top users - number of sessions 
  * Largest file encountered [bytes]
  * Web browser stats [%]
  * Operating system stats [%]
- [x] wontfix Provide this info to Grafana
- [x] wontfix Update diagram

**Comment by robertoostenveld** [comment]
As a product owner in **only** want a log file - nothing more fancy. Having data in Grafana does not contribute to the product value for the users. There are more important things to work on, e.g. reaching out to lab managers and users with instruction and documentation.

**Comment by hurngchunlee** [comment]
@rutgervandeelen I tend to agree with Robert after reviewing your implementation.  I think it is bloated with adding a PostgreSQL database just for persistent the information about user activities.  I don't think it's necessary even with Grafana.  Let's re-discuss it.

@robertoostenveld The reasons not relying on log files are the following: 

- the log files are not persistent with containers at the moment (i.e. the log is printed to stdout and flushed automatically after it reaches a size limitation).
- even we want to persist the log file, we still have to visit the log content anyway to see if the logged information is sufficient for statistics.
-  in the future, when we consolidate the authentication mechanism (which Jascha has developed for the new product database), the log will no longer contain user identifier, making it impossible to identify who did what with the streamer.

Originally I thought it can be implemented easily by having the existing mechanism (which is based on Grafana) pulling static data from the streamer periodically and store the statistics somewhere else.

**Comment by rutgervandeelen** [comment]
@hurngchunlee @robertoostenveld I have spent one day to refactor the `streamer-ui-server` part and to gather diagnostic information. It works (i.e. I have access to the data I want) and I will stop this activity now. Displaying the diagnostic information in Grafana is not implemented and not required, but might be interesting in the future.

Of course, the `streamer-ui-server` can be optimized in the way that Hong has in mind, but I propose to leave the code as it is now.

Now I am going to focus on reaching out to the lab managers and test users, and improve the instructions and documentation.
